let ad ='leyla';
let yemek ='pizza';
let email ='leila@gmail.com';
console.log('menim email adresim ' + email );
console.log('leyla ' + yemek + ' yemeyi cox xoslayir');
console.log(ad +'nin email adresi ' + email );
console.log( yemek + ' ' + ad + 'nin sevimli yemeyidir');
// let elmaddin =508408000;
// let hemid =558148014;
// let anar =507590708;
// let masin = 'mercedes';
// console.log(masin);
